spring.application.name=api-gateway

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.instance.hostname=localhost


server.port=9090


# =========================
# Spring Cloud Gateway
# =========================

spring.cloud.gateway.server.webflux.routes[0].id=EMPLOYEE
spring.cloud.gateway.server.webflux.routes[0].uri=lb://EMPLOYEE-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/employees/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=AuthFilter
spring.cloud.gateway.server.webflux.routes[0].filters[1].name=CircuitBreaker
spring.cloud.gateway.server.webflux.routes[0].filters[1].args.name=EMPLOYEE-SERVICE
spring.cloud.gateway.server.webflux.routes[0].filters[1].args.fallbackUri=forward:/employeeServiceFallback


spring.cloud.gateway.server.webflux.routes[1].id=ADDRESS
spring.cloud.gateway.server.webflux.routes[1].uri=lb://ADDRESS-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/addresses/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=AuthFilter
spring.cloud.gateway.server.webflux.routes[1].filters[1].name=CircuitBreaker
spring.cloud.gateway.server.webflux.routes[1].filters[1].args.name=ADDRESS-SERVICE
spring.cloud.gateway.server.webflux.routes[1].filters[1].args.fallbackUri=forward:/addressServiceFallback


spring.cloud.gateway.server.webflux.routes[2].id=AUTH
spring.cloud.gateway.server.webflux.routes[2].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/auth/**

# =========================
# Resilience4j TimeLimiter
# =========================
#
resilience4j.timelimiter.instances.EMPLOYEE-SERVICE.timeoutDuration=5s
resilience4j.timelimiter.instances.ADDRESS-SERVICE.timeoutDuration=5s

## =========================
## Resilience4j CircuitBreaker
## =========================

resilience4j.circuitbreaker.instances.EMPLOYEE-SERVICE.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.EMPLOYEE-SERVICE.eventConsumerBufferSize=10
resilience4j.circuitbreaker.instances.EMPLOYEE-SERVICE.slidingWindowSize=5
resilience4j.circuitbreaker.instances.EMPLOYEE-SERVICE.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.EMPLOYEE-SERVICE.failureRateThreshold=50
resilience4j.circuitbreaker.instances.EMPLOYEE-SERVICE.waitDurationInOpenState=6s
resilience4j.circuitbreaker.instances.EMPLOYEE-SERVICE.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.instances.EMPLOYEE-SERVICE.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.EMPLOYEE-SERVICE.slidingWindowType=COUNT_BASED


resilience4j.circuitbreaker.instances.ADDRESS-SERVICE.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.ADDRESS-SERVICE.eventConsumerBufferSize=10
resilience4j.circuitbreaker.instances.ADDRESS-SERVICE.slidingWindowSize=5
resilience4j.circuitbreaker.instances.ADDRESS-SERVICE.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.ADDRESS-SERVICE.failureRateThreshold=50
resilience4j.circuitbreaker.instances.ADDRESS-SERVICE.waitDurationInOpenState=6s
resilience4j.circuitbreaker.instances.ADDRESS-SERVICE.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.instances.ADDRESS-SERVICE.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.ADDRESS-SERVICE.slidingWindowType=COUNT_BASED

## =========================
## Actuator / Management
## =========================

management.endpoints.web.exposure.include=health,info,metrics,circuitbreakers
management.health.circuitbreakers.enabled=true
management.endpoint.health.show-details=always

